# source "https://cdn.cocoapods.org/"
source "https://github.com/CocoaPods/Specs.git"
# source "https://github.com/JiaDingYi/Menta-Specs.git"

platform :ios, '12.0'

inhibit_all_warnings!

target 'MentaDemo' do
  # demo需要 SDK并不需要
  pod 'SDWebImage', '~> 5.0'
  pod 'Masonry'

  pod 'MentaVlionBaseSDK',  '6.00.01'
  pod 'MentaUnifiedSDK',    '6.00.01'
  pod 'MentaVlionSDK',      '6.00.01'

  pod 'MentaVlionAdapter',  '6.00.01'
  pod 'MentaJDYunAdapter',  '6.00.01'
  pod 'MentaBaiduAdapter',  '6.00.01'
  pod 'MentaGDTAdapter',    '6.00.01'
  pod 'MentaTanxAdapter',   '6.00.01'
  pod 'MentaCSJAdapter',    '6.00.01'
  pod 'MentaSigmobAdapter', '6.00.01'
  pod 'MentaKSAdapter',     '6.00.01'

end
