# source "https://cdn.cocoapods.org/"
source "https://github.com/CocoaPods/Specs.git"
# source "https://github.com/JiaDingYi/Menta-Specs.git"

platform :ios, '12.0'

inhibit_all_warnings!

target 'MentaDemo' do
  # demo需要 SDK并不需要
  pod 'SDWebImage', '~> 5.0'
  pod 'Masonry'

  pod 'MentaVlionBaseSDK',  '5.20.23'
  pod 'MentaUnifiedSDK',    '5.20.23'
  pod 'MentaVlionSDK',      '5.20.23'

  pod 'MentaVlionAdapter',  '5.20.23'
  pod 'MentaJDYunAdapter',  '5.20.23'
  pod 'MentaBaiduAdapter',  '5.20.23'
  pod 'MentaGDTAdapter',    '5.20.23'
  pod 'MentaTanxAdapter',   '5.20.23'
  pod 'MentaCSJAdapter',    '5.20.23'
  pod 'MentaSigmobAdapter', '5.20.23'

end
