platform :ios, '12.0'
#source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'MentaDropDemo' do

pod 'SDWebImage', '~> 5.0'
pod 'Masonry'
pod 'MentaTanxSDK', '3.2.0.1'
pod 'JADYun', '2.5.6'
pod 'Ads-CN', '5.9.2.0'
pod 'GDTMobSDK', '4.14.63'
pod 'BaiduMobAdSDK', '5.331'
end





